### ISSUE TITLE
Search() function and associated query parameters

### ISSUE THREAD

**Issue by rbastic** [rbastic/dyndao#53]
For specifying queries that are more complex than "WHERE KEY1 = VALUE1 AND KEY2= VALUE2".

Support LIMIT, ORDER BY, GROUP BY. 

The hot debate: JOINs.

Some prior art with compatible licensing:

https://github.com/doug-martin/goqu - just a SQL builder
https://godoc.org/github.com/jinzhu/gorm
https://github.com/eaigner/hood
https://github.com/Masterminds/squirrel
https://github.com/umisama/go-sqlbuilder
https://github.com/shuoli84/sqlm

**Comment by rbastic2** [comment]
SQLBuilder is good enough, with the new builder.go. Not going any further. Dyndao is not a panacea for dealing with impedance mismatch.
