### ISSUE TITLE
Consider adding column Length (and Precision, for floats) as a parameter to the Is*Type() functions

### ISSUE THREAD

**Issue by rbastic** [rbastic/dyndao#69]
There are situations where these things are important (due to ambiguity in type affinity.)

**Comment by rbastic2** [comment]
Also consider adding LengthIsINt()

**Comment by rbastic2** [comment]
See https://github.com/rbastic/dyndao/issues/62: Then we can support VARCHAR(MAX) in MSSQL, for example.

That issue has been folded into this one.
