### ISSUE TITLE
Consider support for JOINs

### ISSUE THREAD

**Issue by rbastic** [rbastic/dyndao#81]
Otherwise, is it really a 'relational' mapper?

What's the point if we have nested object save but don't have great support for nested object load?

Etc etc., insert/cue more pontifications and philosophical ranting about ORM quagmires in general.

**Comment by rbastic2** [comment]
JOINs are a contentious and complex issue. The existing design is already quite complex due to dynamic schemas, arbitrary objects, and so on. They will not be implemented at this stage.
