### ISSUE TITLE
Refactor getSQLGen()

### ISSUE THREAD

**Issue by rbastic** [rbastic/dyndao#88]
These types of functions should live in the adapter's code, since every user would have to replicate them otherwise.

**Comment by rbastic** [comment]
Debating just putting a 'new' sub-package, like 'core/new', and stuffing the GetSQLGen() function in there.

**Comment by rbastic2** [comment]
More thoughts: discussed this with Rob a while ago, perhaps I can simply refactor the underlying Go code for the system to prevent this from being such an issue. Maybe this is all stemming from my poor design.
